name: cd

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/*'
      - '.github/workflows/CD.yml'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@master
      -
        uses: actions/configure-pages@v3
      -
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'src'
      -
        id: deployment
        uses: actions/deploy-pages@v2
