name: cd

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/*'
      - '.github/workflows/CD.yml'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@master
        with:
          repository: gamelly/gly-engine
          ref: develop
      - 
        uses: actions/checkout@master
        with:
          path: game
      - 
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: '5.4'
      - 
        run: |
          ./cli.sh build --core native --bundler
      - 
        run: |
          cp game/src/* dist
      -
        uses: actions/configure-pages@v3
      -
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'dist'
      -
        id: deployment
        uses: actions/deploy-pages@v2
